#!/bin/bash
# Quick Test Script for UDP Login System

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         UDP LOGIN SYSTEM - QUICK TEST GUIDE               ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}📋 PRE-TEST CHECKLIST:${NC}"
echo "  ☐ Godot project ready (Login.tscn)"
echo "  ☐ Python virtual environment activated"
echo "  ☐ Camera not in use by other apps"
echo "  ☐ Port 5000 available"
echo ""

echo -e "${YELLOW}🧪 TEST 1: UDP Fragmentation Test${NC}"
echo "  This tests packet fragmentation without Godot"
echo ""
echo -e "${GREEN}Command:${NC}"
echo "  cd \"/Users/samudera/Bagja/Kuliah/Luar Mata Kuliah/Pipeline\""
echo "  python test_udp_fragmentation.py"
echo ""
echo -e "${CYAN}Expected Output:${NC}"
echo "  ✅ UDP socket created"
echo "  ✅ Camera opened"
echo "  📸 Frame size: 640x480 (or similar)"
echo "  💾 JPEG size: ~XX KB"
echo "  📦 Will send N packet(s)"
echo "  ✅ Frame sent successfully!"
echo ""

echo -e "${YELLOW}🎮 TEST 2: Full Login Flow${NC}"
echo "  This tests complete Python→Godot integration"
echo ""
echo -e "${GREEN}Step 1: Start Godot${NC}"
echo "  1. Open Godot project"
echo "  2. Load Scene/Login.tscn"
echo "  3. Press Play (F5)"
echo "  4. Click 'CONNECT CAMERA' button"
echo "  5. Wait for 'UDP Port: Listening' status"
echo ""
echo -e "${GREEN}Step 2: Start Python${NC}"
echo "  cd mediapipe_app"
echo "  source ../mediapipe_env/bin/activate"
echo "  python login.py"
echo ""
echo -e "${CYAN}Expected Behavior:${NC}"
echo "  📡 Python: 'UDP socket created: 127.0.0.1:5000'"
echo "  🎥 Python: 'Camera aktif - Streaming dimulai...'"
echo "  📺 Godot: Video appears in 16:9 aspect ratio"
echo "  👤 Python: 'Face detected: X/60 frames' (if face in view)"
echo "  📊 Godot: 'Face Detected: XX%' status updates"
echo "  🔐 Godot: LOGIN button enables at 50% progress"
echo "  ✅ Python: 'LOGIN BERHASIL!' after 60 frames"
echo "  🚀 Godot: Transitions to Main_UI.tscn"
echo ""

echo -e "${YELLOW}🔧 TROUBLESHOOTING${NC}"
echo ""
echo -e "${RED}Problem: Port already in use${NC}"
echo -e "${GREEN}Solution:${NC}"
echo "  lsof -i :5000          # Find process using port 5000"
echo "  kill -9 <PID>          # Kill that process"
echo ""
echo -e "${RED}Problem: No video in Godot${NC}"
echo -e "${GREEN}Solution:${NC}"
echo "  1. Check Godot console for errors"
echo "  2. Verify 'CONNECT CAMERA' was clicked"
echo "  3. Run test_udp_fragmentation.py first"
echo "  4. Check firewall allows port 5000"
echo ""
echo -e "${RED}Problem: Camera access error${NC}"
echo -e "${GREEN}Solution:${NC}"
echo "  1. Close Zoom, Teams, Skype, etc"
echo "  2. Check System Preferences > Privacy > Camera"
echo "  3. Grant permission to Terminal"
echo "  4. Try: python test_camera.py"
echo ""
echo -e "${RED}Problem: Fragmented/corrupted video${NC}"
echo -e "${GREEN}Solution:${NC}"
echo "  1. Edit login.py → self.jpeg_quality = 60"
echo "  2. Edit login.py → time.sleep(0.001) instead of 0.0005"
echo "  3. Check network: ping 127.0.0.1"
echo ""

echo -e "${CYAN}📁 IMPORTANT FILES:${NC}"
echo "  Python:  mediapipe_app/login.py"
echo "  Godot:   Godot_Project/Scripts/login.gd"
echo "  Test:    test_udp_fragmentation.py"
echo "  Docs:    UDP_IMPLEMENTATION_GUIDE.md"
echo "  Summary: UDP_CHANGES_SUMMARY.md"
echo ""

echo -e "${YELLOW}⚙️  CONFIGURATION${NC}"
echo ""
echo -e "${CYAN}login.py settings:${NC}"
echo "  udp_host = '127.0.0.1'      # Target host"
echo "  udp_port = 5000             # Target port"
echo "  max_packet_size = 60000     # 60KB chunks"
echo "  jpeg_quality = 80           # JPEG quality"
echo ""
echo -e "${CYAN}login.gd settings:${NC}"
echo "  var udp_port := 5000        # Listen port"
echo "  var timeout_duration := 3.0 # Timeout (seconds)"
echo "  var frame_timeout := 1.0    # Frame reassembly timeout"
echo ""

echo -e "${GREEN}🚀 QUICK START:${NC}"
echo ""
echo "# Option A: Test fragmentation only"
echo "python test_udp_fragmentation.py"
echo ""
echo "# Option B: Full login flow"
echo "# Terminal 1 (Godot): Open Login.tscn → Play → Click CONNECT"
echo "# Terminal 2 (Python):"
echo "cd mediapipe_app && source ../mediapipe_env/bin/activate && python login.py"
echo ""

echo -e "${CYAN}📊 PERFORMANCE METRICS:${NC}"
echo "  Target FPS:  15-30 FPS"
echo "  Latency:     ~50-100ms"
echo "  Bandwidth:   ~500KB-1MB per second"
echo "  Packet size: 60KB max (safe for UDP)"
echo ""

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║                    HAPPY TESTING! 🎉                      ║"
echo "╚═══════════════════════════════════════════════════════════╝"
